### PR TITLE
jestの導入

### PR DESCRIPTION
**Pull request by kobakazu0429**
# WHY
計算系の関数が不安なので

# WHAT
## やったこと
- [x] jestの導入
- [x] add test `parsePlayTime()` in RadioCardPlayButton
- [x] add test `calcProgress()` in RadioCardPlayButton
- [x] CircleCIでもテストをするようにした(してもらった)

## やってないこと
なし

### CODE REVIEW

**Comment by euglena1215** [comment]
TSLint analysis of cfa97a81f4a322e2c5cc650662153782783c77e5 failed.
Visit the [analysis results page](https://sider.review/gh/repos/108558043/pulls/387) to review [error log](https://sider.review/gh/repos/108558043/pulls/387/logs/d29d61b7-8ed6-4300-ac36-ca64dead7276).

<sub>posted by Sider</sub>

**Comment by euglena1215** [comment]
TSLint analysis of 2cb87e4343ec48bfe47d61d06075467a9c9d317a failed.
Visit the [analysis results page](https://sider.review/gh/repos/108558043/pulls/387) to review [error log](https://sider.review/gh/repos/108558043/pulls/387/logs/343f7b64-5a83-4476-b23a-c2057a7e9875).

<sub>posted by Sider</sub>

**Comment by euglena1215** [comment]
TSLint analysis of 4fa28fca4a143033439eb38f2638493292b3d987 failed.
Visit the [analysis results page](https://sider.review/gh/repos/108558043/pulls/387) to review [error log](https://sider.review/gh/repos/108558043/pulls/387/logs/c1023ed4-ef03-4754-92af-47507dd39f14).

<sub>posted by Sider</sub>

**Comment by euglena1215** [comment]
TSLint analysis of 3535fe700b71bdc2e4c665e7a607d759f3b5aa4b failed.
Visit the [analysis results page](https://sider.review/gh/repos/108558043/pulls/387) to review [error log](https://sider.review/gh/repos/108558043/pulls/387/logs/65b89361-cf20-4b3f-8191-349e3f45a8d5).

<sub>posted by Sider</sub>

**Comment by euglena1215** [comment]
TSLint analysis of a3eb320e9018d5a9b6d83d7d3d2ccf2e47c8ca68 failed.
Visit the [analysis results page](https://sider.review/gh/repos/108558043/pulls/387) to review [error log](https://sider.review/gh/repos/108558043/pulls/387/logs/ca91eb1b-d732-4293-b9cb-5eaf7ad9a667).

<sub>posted by Sider</sub>

**Comment by euglena1215** [comment]
TSLint analysis of 3ebf8ba841e041773703878cf7d098587e93427e failed.
Visit the [analysis results page](https://sider.review/gh/repos/108558043/pulls/387) to review [error log](https://sider.review/gh/repos/108558043/pulls/387/logs/ef71316f-dfe0-45bb-bddd-6b2fcd3a1be5).

<sub>posted by Sider</sub>

**Comment by euglena1215** [comment]
TSLint analysis of a0f24615571786a0b11120517f7ffb8cb13584af failed.
Visit the [analysis results page](https://sider.review/gh/repos/108558043/pulls/387) to review [error log](https://sider.review/gh/repos/108558043/pulls/387/logs/a9ae5393-1b73-4ae1-a9e6-4aa35f3886a0).

<sub>posted by Sider</sub>

**Review by euglena1215 — APPROVED** [review]
もったいないなと思ったのでcircleciのconfig追加してCIでもテスト走るようにしました
LGTM!!!

**Comment by kobakazu0429** [comment]
お疲れ様です！ありがとうございます！

**Pull request merged**
